- INSTALL.md
- TUNING_GUIDE_ArduCopter.md
- TUNING_GUIDE_ArduPlane.md
- TUNING_GUIDE_Heli.md
- TUNING_GUIDE_Rover.md
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
- install_linux.sh
- install_macos.sh
So that users do not need to close the window, just click outside of it
> FEATURE: close bitmask window when out-of-focus

- ardupilot_methodic_configurator/frontend_tkinter_software_update.py
- ardupilot_methodic_configurator/middleware_software_updates.py
- tests/test_frontend_tkinter_software_update.py
- tests/test_middleware_software_updates.py
remove PR and author information
add pytests
increase window size
> Add scrollable changelog

- ardupilot_methodic_configurator/configuration_steps_ArduCopter.json
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
It now requires a double-click to open the bitmask editing window
> FEATURE: allow editing bitmask values numerically

- ardupilot_methodic_configurator/configuration_steps_ArduCopter.json
Ardupilot Methodic Configurator now correctly identifies the MCU series (F4,F7 or H7) of each of the 271 currently supported flight controller boards.
So use that information to correctly configure the best suited logging parameters.
> FEATURE: Use MCU series to make parameter values decisions

- windows/ardupilot_methodic_configurator.iss
This pull request includes a small change to the `windows/ardupilot_methodic_configurator.iss` file. The change adds a new source file to the installation script.
* [`windows/ardupilot_methodic_configurator.iss`](diffhunk://#diff-8c51dfc5bddb9d3c3c14f0685ab9e542fa6c9439911fcd5d0bd9bcc785ae4200R90): Added the `vehicle_components_schema.json` file to the list of source files to be included in the installation.
> Add missing vehicle_components_schema.json file

- ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- tests/test_backend_filesystem_vehicle_components.py
This pull request includes changes to improve error handling and messaging when saving vehicle components data in the `ardupilot_methodic_configurator` project. The most important changes include modifying the return type of the `save_vehicle_components_json_data` method, updating the error messages in the frontend, and adjusting the corresponding tests.
Improvements to error handling and messaging:
* [`ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py`](diffhunk://#diff-4d082af14c1239b3a9772b04b19d0ba7bc6a11c6675c8dae7d127dcb65ab7d92L103-R152): Modified the `save_vehicle_components_json_data` method to return a tuple of `(bool, str)` indicating whether an error occurred and the error message. Added detailed error messages for different exceptions.
Frontend updates: …
> Improve error messages when saving vehicle_components.json file

- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py
- ardupilot_methodic_configurator/frontend_tkinter_directory_selection.py
This pull request includes several changes to enhance the functionality and user interface of the ArduPilot Methodic Configurator. The key updates focus on adding new options for vehicle configuration and improving the internal handling of component data.
* Added two new options, `blank_template_data` and `infer_comp_specs_and_conn_from_fc_params`, to the `VehicleDirectorySelectionWindow` class, allowing users to create a blank vehicle configuration or infer component specifications from flight controller parameters. (`[[1]](diffhunk://#diff-a905b22cef87c69aa1b10b35af17721b5aa0ad2a995994a4360e3353e4266de8R239-R240)`, `[[2]](diffhunk://#diff-a905b22cef87c69aa1b10b35af17721b5aa0ad2a995994a4360e3353e4266de8R293-R318)`, `[[3]](diffhunk://#diff-a905b22cef87c69aa1b10b35af17721b5aa0ad2a995994a436 …
> Allow blank component editor, allow separate component inference

- .vscode/tasks.json
- ARCHITECTURE.md
- SetupDeveloperPC.bat
- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/backend_filesystem.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_directory_selection.py
- tests/test_annotate_params.sh
- tests/test_backend_filesystem.py
- tests/test_param_pid_adjustment_update.sh
This pull request includes several changes to improve the functionality and usability of the `ardupilot_methodic_configurator` project. The most important changes include updates to the test configurations, enhancements to the template copying process, and adjustments to the internationalization settings.
* [`.vscode/tasks.json`](diffhunk://#diff-7d76d7533653c23b753fc7ce638cf64bdb5e419927d276af836d3a03fdf1745aR176-R233): Added new tasks for running `pytest` with coverage reports in both HTML format for Linux and Windows environments.
* `tests/test_annotate_params.sh` and `tests/test_param_pid_adjustment_update.sh`: Changed the test runner from `unittest` to `pytest` for better compatibility and reporting. [[1]](diffhunk://#diff-58255db78cd23b42df2c5c8acabcaaf7bbca3238ec1ff822d7626713ac44bf …
> Blank parameter change reason

- .github/workflows/pytest.yml
- ardupilot_methodic_configurator/frontend_tkinter_base.py
- ardupilot_methodic_configurator/frontend_tkinter_connection_selection.py
- ardupilot_methodic_configurator/frontend_tkinter_pair_tuple_combobox.py
- tests/test_frontend_tkinter_base.py
- tests/test_frontend_tkinter_pair_tuple_combobox.py
This pull request includes updates to the test coverage threshold and the addition of comprehensive unit tests for the `PairTupleCombobox` and `PairTupleComboboxTooltip` classes in the `ardupilot_methodic_configurator` package.
Updates to test coverage:
* [`.github/workflows/pytest.yml`](diffhunk://#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL139-R139): Increased the coverage threshold from 41% to 51%.
Addition of unit tests:
* [`tests/test_frontend_tkinter_pair_tuple_combobox.py`](diffhunk://#diff-703b25e1d4d0ce9113a029c862c910d3557ed06dbe8dff4a241b2b441ea05670R1-R240): Added a new test file with detailed unit tests for `PairTupleCombobox` and `PairTupleComboboxTooltip` classes, including tests for initialization, tooltip creation, tooltip destruction, key …
> Cmd completion docs

- ardupilot_methodic_configurator/frontend_tkinter_component_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- tests/test_frontend_tkinter_component_editor_base.py
This pull request includes significant changes to the `ardupilot_methodic_configurator` project, focusing on enhancing the component editor and adding comprehensive tests. The most important changes include renaming methods for clarity, handling window closing events, and adding new tests.
fixes #250
fixes #248 
Enhancements to component editor:
* [`ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py`](diffhunk://#diff-7f3397e9355b08ace5f25e2a3f881656ea2b7b934ae6de417f3cac9e9e320dabL116-R121): Renamed `save_data` to `validate_and_save_component_json` and added a new method `save_component_json` to separate validation and saving logic. [[1]](diffhunk://#diff-7f3397e9355b08ace5f25e2a3f881656ea2b7b934ae6de417f3cac9e9e320dabL116-R121) …
> On component editor window close action ask user if he wants to save

- .github/workflows/bump_version_and_tag.yml
- .github/workflows/i18n-extract.yml
- .github/workflows/markdown-lint.yml
- .github/workflows/mypy.yml
- .github/workflows/pylint.yml
- .github/workflows/pyright.yml
- .github/workflows/pytest.yml
- .github/workflows/renovate_pre_commit_hooks.yml
- .github/workflows/reuse.yml
- .github/workflows/update_flightcontroller_ids.yml
- .github/workflows/update_magfit_pdef_xml.yml
- .github/workflows/update_mo_files.yml
This pull request includes various changes to multiple GitHub Actions workflow files, primarily focusing on updating permissions and improving automation for creating pull requests. The most important changes are summarized below:
* [`.github/workflows/bump_version_and_tag.yml`](diffhunk://#diff-fbcb32501342e19f048cf36761f62c5f8c3a2bd0c9ebb2ae579c8d606eee6f7cL16-R23): Changed `contents` permission from `write` to `read` and added `contents: write` permission within the job.
* [`.github/workflows/i18n-extract.yml`](diffhunk://#diff-2d579475fad26e1d128dc2d45de56003325cc16a838bd385822f9179d1254b6eR17-R24): Added `contents: read` permission and updated job permissions to `contents: write` and `pull-requests: write`.
* `.github/workflows/markdown-lint.yml`, `.github/workflows/mypy.yml`, …
> Restrict CI permissions. Create PR instead of pushing to master

- .github/workflows/gitavscan.yml
- .github/workflows/renovate_pre_commit_hooks.yml
- renovate-config.json
This pull request includes changes to the GitHub workflows and the Renovate configuration to improve permissions and update configuration settings.
Improvements to GitHub workflows:
* [`.github/workflows/gitavscan.yml`](diffhunk://#diff-3f851474414ec7ea0b7f8ded7ca51c357ef37ab338b7d7e93c3a619f5f139417R10-R12): Added default limited permission for contents to the `release` workflow.
* [`.github/workflows/renovate_pre_commit_hooks.yml`](diffhunk://#diff-a91cb70ee674209a9822a445114d191b6de7b703216a452d61a1b92a20ea32f9L9-R16): Updated comments for permissions to clarify job-specific permissions for creating branches and pull requests.
Updates to Renovate configuration:
* [`renovate-config.json`](diffhunk://#diff-26dbe544619f8f0e948aabd7f14bb061b657807812430c7b5f0b1ae8972550bdL2-R2): Changed …
> Migrate renovate configuration

- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/backend_filesystem.py
- ardupilot_methodic_configurator/frontend_tkinter_directory_selection.py
- ardupilot_methodic_configurator/locale/de/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/it/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/ja/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/pt/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/zh_CN/LC_MESSAGES/ardupilot_methodic_configurator.po
Fixes #249
This pull request includes changes to the `ardupilot_methodic_configurator` project to enhance the handling of component data during vehicle initialization and creation. The most important changes include modifying the `re_init` method to support a new parameter for wiping component data and updating related method calls to incorporate this new parameter.
Enhancements to vehicle initialization:
* [`ardupilot_methodic_configurator/backend_filesystem.py`](diffhunk://#diff-cf28409654b00ab8706721d7366feaf693978b04612204ba7b945adac7563716L102-R112): Modified the `re_init` method to include a new `blank_component_data` parameter, which, when set to `True`, wipes the component information and saves the vehicle components JSON data.
Updates to method calls:
* …
> fix(templates): Fix issue #249

- .vscode/settings.json
This pull request includes a small change to the `.vscode/settings.json` file. The change removes the line `"ruff.lint.run": "onSave",`, which previously configured the Ruff linter to run on file save. 
* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357L60): Removed the `"ruff.lint.run": "onSave",` setting.
> Deactivate deprecated real-time ruff linter

- .github/workflows/update_vehicle_templates.yml
This pull request includes updates to the GitHub Actions workflow for updating vehicle templates. The most important changes involve setting up the UV system Python version, installing UV, and ensuring dependencies are installed.
Enhancements to the workflow:
* [`.github/workflows/update_vehicle_templates.yml`](diffhunk://#diff-7c38991ace082c212b93eaaf4c47c57b1253e060a15a5a5f69cae67a0c1b98b3R24): Added an environment variable `UV_SYSTEM_PYTHON` to the job configuration.
* [`.github/workflows/update_vehicle_templates.yml`](diffhunk://#diff-7c38991ace082c212b93eaaf4c47c57b1253e060a15a5a5f69cae67a0c1b98b3R34-R49): Included a step to install UV and set the Python version using `astral-sh/setup-uv`.
* [`.github/workflows/update_vehicle_templates.yml`](diffhunk://#diff-7c38991ace082c212b93eaaf4c …
> Install deps required by the update_vehicle_templates.py script

- .github/workflows/update_vehicle_templates.yml
This pull request includes changes to the `.github/workflows/update_vehicle_templates.yml` file to refine the file types being tracked for changes in the vehicle templates directory.
Changes in `jobs:`:
* [`.github/workflows/update_vehicle_templates.yml`](diffhunk://#diff-7c38991ace082c212b93eaaf4c47c57b1253e060a15a5a5f69cae67a0c1b98b3L56-R57): Updated the `git add` command to specifically track `.param` and `.json` files within the `ardupilot_methodic_configurator/vehicle_templates` directory.
> Do not add apm.pdef.xml files to git

- ardupilot_methodic_configurator/backend_filesystem.py
This pull request includes an important change to the `ardupilot_methodic_configurator/backend_filesystem.py` file to improve error handling and logging when converting parameter values.
Error handling and logging improvements:
* [`ardupilot_methodic_configurator/backend_filesystem.py`](diffhunk://#diff-cf28409654b00ab8706721d7366feaf693978b04612204ba7b945adac7563716R211-R219): Added a nested try-except block to handle cases where parameter values cannot be converted to either integers or floats. If both conversions fail, a warning is logged, and users are prompted to file a bug report.
> Warn about invalid apm.pdef.xml parameter metadata, but do not crash

- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/backend_internet.py
- tests/test_backend_internet.py
This pull request introduces a new function `verify_and_open_url` to the `ardupilot_methodic_configurator` project, which verifies if a URL is accessible and opens it in the default web browser if successful. Additionally, several tests have been added to ensure the function works correctly under different conditions.
New functionality:
* [`ardupilot_methodic_configurator/backend_internet.py`](diffhunk://#diff-a8715254fad02f2903e2f2c68f8de5501bf52c2f6aab3fb2d3c091202cb59b40R200-R245): Added the `verify_and_open_url` function to verify URL accessibility and open it in the default web browser.
Integration into existing code:
* [`ardupilot_methodic_configurator/__main__.py`](diffhunk://#diff-07c8aae629798ce99b3a341b36fe9273c6afcf8de3d503dfbc9e720055f5630fR132-R141): Integrated the …
> Avoid 404 pages if the flight controller README.md file does not exist

- TUNING_GUIDE_ArduCopter.md
This pull request includes updates to the `TUNING_GUIDE_ArduCopter.md` file to clarify terminology and add additional checks for potential issues. The most important changes include refining the description of oscillation problems and adding checks for ESC temperatures.
Clarifications and additional checks:
* [`TUNING_GUIDE_ArduCopter.md`](diffhunk://#diff-25057261d62a266a9e263de6a22afbff4c4b7d12ea12f4c4bbb4a6ff32012b4fL654-R668): Updated the terminology from "oscillation" to "output oscillation" to provide clearer guidance.
* [`TUNING_GUIDE_ArduCopter.md`](diffhunk://#diff-25057261d62a266a9e263de6a22afbff4c4b7d12ea12f4c4bbb4a6ff32012b4fL654-R668): Added "Excessively hot ESCs after flight" as a sign of output oscillation issues.
* …
> Add ESC temperature to the checklist.

- ardupilot_methodic_configurator/backend_filesystem.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
- pyproject.toml
This pull request includes several changes to the `ardupilot_methodic_configurator` project, focusing on parameter file handling and dependency updates. The most important changes involve modifying how parameter files are exported and annotated, updating dependencies, and handling parameter edits in the frontend.
Changes to parameter file handling:
* [`ardupilot_methodic_configurator/backend_filesystem.py`](diffhunk://#diff-cf28409654b00ab8706721d7366feaf693978b04612204ba7b945adac7563716L669-R671): Modified the `update_and_export_vehicle_params_from_fc` method to include an option for annotating documentation into parameter files.
* [`ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py`](diffhunk://#diff-66416537a8c3d05fc24b29ee4b158b15e4bade6fe86f9229e780081570a279b5L749- …
> Customer requirements to annotate all files at once

- ardupilot_methodic_configurator/locale/de/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/it/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/ja/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/pt/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/zh_CN/LC_MESSAGES/ardupilot_methodic_configurator.po
This pull request includes updates to the German and Italian translation files for the `ardupilot_methodic_configurator` project. The changes primarily involve adding previously missing translations for various messages.
Translation updates:
* Added German translations for error messages and instructions in `ardupilot_methodic_configurator.po` [[1]](diffhunk://#diff-e5a670f01a48bd932948f31f1faa9864eec8b91a4e773129f71cccffc577df99L112-R116) [[2]](diffhunk://#diff-e5a670f01a48bd932948f31f1faa9864eec8b91a4e773129f71cccffc577df99L225-R225) [[3]](diffhunk://#diff-e5a670f01a48bd932948f31f1faa9864eec8b91a4e773129f71cccffc577df99L368-R372) [[4]](diffhunk://#diff-e5a670f01a48bd932948f31f1faa9864eec8b91a4e773129f71cccffc577df99L384-R408) [[5]](diffhunk://#diff-e5a670f01a48bd932948f31f1faa9864eec8b91 …
> Updated all languages

- ardupilot_methodic_configurator/frontend_tkinter_component_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- tests/test_frontend_tkinter_template_overview.py
This pull request includes significant updates to the `tests/test_frontend_tkinter_template_overview.py` file, primarily adding new test cases for the `TemplateOverviewWindow` class and improving the test coverage for various functionalities.
* Added test case to verify the initialization of `TemplateOverviewWindow` with the correct properties.
* Added test case to ensure that double-clicking a row in the treeview stores the template directory correctly.
* Added test case to check that changing row selection updates the image display appropriately.
* Added test case to verify that sorting by column works correctly, including handling numeric values.
* Added test case to handle the display of vehicle images, both when the image is present and when it is missing.
* Added test case to ensure …
> test(template overview): Add pytest

- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py
- tests/test_frontend_tkinter_parameter_editor.py
This pull request includes several changes to the `ardupilot_methodic_configurator` project, focusing on improving the tkinter parameter editor and adding unit tests for better coverage. The most important changes include adding a new method to handle dialog choices, refactoring button command handling, and introducing comprehensive unit tests for the `ParameterEditorWindow` class.
Refactoring and improvements:
* [`ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py`](diffhunk://#diff-66416537a8c3d05fc24b29ee4b158b15e4bade6fe86f9229e780081570a279b5R451-R454): Added the `__handle_dialog_choice` method to centralize dialog choice handling and refactored button commands to use this new method. [[1]](diffhunk://#diff-66416537a8c3d05fc24b29ee4b158b15e4bade6fe86f9229e780081570a2 …
> Add initial test code

- .github/workflows/pytest.yml
This pull request includes updates to the coverage thresholds in the `pytest` workflow configuration. The changes increase the required coverage percentage for the project.
Changes to coverage thresholds:
* [`.github/workflows/pytest.yml`](diffhunk://#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL142-R142): Increased the `--fail-under` coverage threshold from 51 to 60.
* [`.github/workflows/pytest.yml`](diffhunk://#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL223-R223): Increased the `thresholdAll` coverage threshold from 0.55 to 0.60.
> Increase the test coverage threshold to 60%

- .github/dependabot.yml
This pull request includes a change to the `.github/dependabot.yml` file to add a new update configuration for the `pip` package ecosystem. This new configuration schedules weekly updates for dependencies located in the `.github/workflows` directory.
* Added a new `pip` package-ecosystem configuration for weekly updates in the `.github/workflows` directory.
> Automate updates of packages used in CI jobs

- .github/workflows/renovate_pre_commit_hooks.yml
- renovate-config.json
This pull request includes a change to the `.github/workflows/renovate_pre_commit_hooks.yml` file to remove the step that creates a pull request for updating pre-commit hooks.
Changes in `jobs:`:
* Removed the step that uses `peter-evans/create-pull-request` to create a pull request for updating pre-commit hooks. This includes the removal of the associated parameters such as `token`, `labels`, `branch`, `title`, `commit-message`, `body`, and `delete-branch`.
> Renovate creates PRs, so no need to do it extra

- ardupilot_methodic_configurator/configuration_steps_ArduCopter.json
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/AirCar_v1/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Chimera7/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/FETtec-5/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/GazeboIrisWithTargetFollow/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X500_V2/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Hoverit_X11+/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Marmotte5v2/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/ReadyToSkyZD550/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Tarot_X4/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/X11_plus/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/diatone_taycan_mxc/4.3.8-params/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/diatone_taycan_mxc/4.4.4-params/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/diatone_taycan_mxc/4.5.x-params/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/diatone_taycan_mxc/4.6.x-params/24_inflight_magnetometer_fit_setup.param
- ardupilot_methodic_configurator/vehicle_templates/Rover/AION_R1/24_inflight_magnetometer_fit_setup.param
This pull request includes multiple changes to the ArduPilot Methodic Configurator, focusing on updating parameter values for various vehicle templates and adding a new derived parameter in the configuration steps. The most important changes are summarized below:
* Added the `ESC_HW_POLES` derived parameter in the `configuration_steps_ArduCopter.json` file to specify the number of poles for the ESC hardware.
* Updated the `MAGH_USE_LOITER` parameter from `0` to `1` across multiple vehicle template files to set a Loiter_unlimited command at the beginning of the mission for checking generated waypoints. This change was applied to the following files:
- `ArduCopter/AirCar_v1/24_inflight_magnetometer_fit_setup.param`
- `ArduCopter/Chimera7/24_inflight_magnetometer_fit_setup.param`
- …
> Correct ESC_HW_POLES and MAGH_USE_LOITER values

- REUSE.toml
- update_flight_controller_ids.py
This pull request includes changes to improve file annotations and update the logic for handling flight controller IDs. The most important changes include adding a new file to the `REUSE.toml` annotations and updating the `update_flight_controller_ids.py` script to use a new prefix list for non-flight controller directories.
File annotations:
* [`REUSE.toml`](diffhunk://#diff-74bd2d6afd7a1f967679adae374ca38fd9745fe6129dc4717a1ab0e388590b08L29-R29): Added `renovate.json` to the list of annotated files.
Flight controller ID updates:
* [`update_flight_controller_ids.py`](diffhunk://#diff-32745db632a2e925795d3266eba628b4d2bfaf006ac6f0facec845d0eda61cb8L35-R38): Introduced a new tuple `NON_FC_PREFIXES` to store prefixes for non-flight controller directories.
* …
> Ignore ap periph

- ardupilot_methodic_configurator/backend_filesystem.py
This pull request includes a change to the `zip_files` method in the `ardupilot_methodic_configurator/backend_filesystem.py` file. The change refactors the method to use a helper function for adding files to the zip archive.
Refactoring of `zip_files` method:
* [`ardupilot_methodic_configurator/backend_filesystem.py`](diffhunk://#diff-cf28409654b00ab8706721d7366feaf693978b04612204ba7b945adac7563716L442-R442): Modified the `zip_files` method to use the `add_configuration_file_to_zip` helper function for adding files to the zip archive.
> Check that a file exists before zipping it

- .github/workflows/renovate_pre_commit_hooks.yml
- renovate-config.json
This pull request includes changes to the `.github/workflows/renovate_pre_commit_hooks.yml` and `renovate-config.json` files to enhance permissions and configuration settings for the Renovate bot.
Improvements to permissions and configuration:
* [`.github/workflows/renovate_pre_commit_hooks.yml`](diffhunk://#diff-a91cb70ee674209a9822a445114d191b6de7b703216a452d61a1b92a20ea32f9R17): Added `issues: write` permission to allow the creation of dashboard issues.
* [`renovate-config.json`](diffhunk://#diff-26dbe544619f8f0e948aabd7f14bb061b657807812430c7b5f0b1ae8972550bdL15-R18): Added `"platform": "github"`, `"includePaths": ["**/.pre-commit-config.yaml"]`, and set `"dependencyDashboard"` to `false` to refine the Renovate configuration.
> Renovate permissions fixes

- .github/workflows/renovate_pre_commit_hooks.yml
- renovate-config.json
This pull request includes changes to the Renovate configuration and workflow files to streamline the process and remove unnecessary steps.
Changes to `.github/workflows/renovate_pre_commit_hooks.yml`:
* Removed the checkout step from the workflow file, simplifying the job steps.
Changes to `renovate-config.json`:
* Removed the `includePaths` and `dependencyDashboard` settings from the configuration file, focusing the configuration on essential settings only.
> Do not checkout the files.

- .github/workflows/renovate_pre_commit_hooks.yml
- renovate-config.json
This pull request includes changes to the `renovate` configuration and workflow files to improve dependency management and token usage. The most important changes are as follows:
* [`.github/workflows/renovate_pre_commit_hooks.yml`](diffhunk://#diff-a91cb70ee674209a9822a445114d191b6de7b703216a452d61a1b92a20ea32f9R19-R25): Added a `Checkout` step using `actions/checkout@v4.2.2` and updated the token from `GITHUB_TOKEN` to `RENOVATE_TOKEN` for the `Self-hosted Renovate` step.
* [`renovate-config.json`](diffhunk://#diff-26dbe544619f8f0e948aabd7f14bb061b657807812430c7b5f0b1ae8972550bdR5): Added the `includePaths` configuration to include `.pre-commit-config.yaml` in the managed paths.
* [`renovate-config.json`](diffhunk://#diff-26dbe544619f8f0e948aabd7f14bb061b657807812430c7b5f0b1ae8972550bdL1 …
> One more renovate fix

- .github/workflows/mypy.yml
- .github/workflows/pytest.yml
- .github/workflows/ruff.yml
- pyproject.toml
This pull request includes several updates to dependencies and configuration files across multiple workflows. The most important changes include updating dependencies in the `mypy`, `pytest`, and `ruff` workflows, adjusting the coverage threshold in the `pytest` workflow, and removing a configuration entry in `pyproject.toml`.
Dependency updates:
* [`.github/workflows/mypy.yml`](diffhunk://#diff-07730f31c368f5e0af82cb7d820dc37ae6a752a0a226f7aee9ebac72dfe41459L26-R26): Updated `types-requests` dependency to version `2.32.0.20250328`.
* [`.github/workflows/pytest.yml`](diffhunk://#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL133-R133): Updated `coverage` dependency to version `7.8.0`.
* [`.github/workflows/ruff.yml`](diffhunk://#diff-2648f2b57520d4056946a7e509a50cfed …
> Use newer SW versions in ci

- .coveragerc
This pull request includes a minor change to the `.coveragerc` file, specifically to the `omit` list. The change corrects the formatting by adding missing commas between file names.
* [`.coveragerc`](diffhunk://#diff-834e9b406d74791ffbafaeec9cc894082cea9739bc347b6ff9f72312c92ebc79L6-R6): Added missing commas between file names in the `omit` list to ensure proper formatting.
> Added missing commas to ignore files in coverage reports

- tests/test_backend_filesystem_program_settings.py
This pull request adds a comprehensive set of unit tests for the `ProgramSettings` class in the `backend_filesystem_program_settings.py` file. These tests cover various functionalities, including file path retrieval, directory creation, user configuration directory handling, settings retrieval and modification, and display usage popup settings.
Key changes include:
* Added tests for `application_icon_filepath` and `application_logo_filepath` methods to verify the correct file paths are returned using mocked `os.path` methods.
* Implemented tests for `create_new_vehicle_dir` method to handle scenarios where the directory already exists or directory creation fails.
* Added tests for `valid_directory_name` method to validate directory names with various characters.
* Created tests for …
> Add program settings tests

- .github/CODEOWNERS
This pull request includes a change to the `.github/CODEOWNERS` file. The change assigns a default owner for the entire repository and provides examples for specifying multiple owners and owners for specific directories.
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R1-R10): Added default owner `@amilcarlucas` for the entire repository and included examples for specifying multiple owners and owners for specific directories.
> Add a codeowners file to automate reviewer assignment

- renovate-config.json
This pull request includes a small change to the `renovate-config.json` file. The change disables the `dependencyDashboard` feature.
* [`renovate-config.json`](diffhunk://#diff-26dbe544619f8f0e948aabd7f14bb061b657807812430c7b5f0b1ae8972550bdL16-R16): Changed the `dependencyDashboard` setting from `true` to `false`.
> Disable renovate dashboard, we only have one application in one repo

- ardupilot_methodic_configurator/locale/de/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/it/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/ja/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/pt/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/zh_CN/LC_MESSAGES/ardupilot_methodic_configurator.po
This pull request includes updates to the localization files for several languages in the `ardupilot_methodic_configurator` project. These changes add missing translations for specific messages related to the download and installation process.
Localization updates:
* [`ardupilot_methodic_configurator/locale/de/LC_MESSAGES/ardupilot_methodic_configurator.po`](diffhunk://#diff-e5a670f01a48bd932948f31f1faa9864eec8b91a4e773129f71cccffc577df99L763-R763): Added missing German translations for messages related to downloading and installing the application. [[1]](diffhunk://#diff-e5a670f01a48bd932948f31f1faa9864eec8b91a4e773129f71cccffc577df99L763-R763) [[2]](diffhunk://#diff-e5a670f01a48bd932948f31f1faa9864eec8b91a4e773129f71cccffc577df99L772-R772)
* …
> Add two new strings

- ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py
- tests/test_backend_filesystem_vehicle_components.py
This pull request includes several changes to the `ardupilot_methodic_configurator` project, focusing on enhancing the `ConfigurationSteps` and `VehicleComponents` functionalities and improving test coverage. The most important changes include refactoring the `_recursively_clear_dict` method, adding new test cases, and importing necessary modules.
Refactoring and bug fixes:
* [`ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py`](diffhunk://#diff-4d082af14c1239b3a9772b04b19d0ba7bc6a11c6675c8dae7d127dcb65ab7d92L458-R467): Refactored the `_recursively_clear_dict` method to handle different data types more explicitly, ensuring numerical values are set to 0 or 0.0, and strings are set to an empty string.
Test coverage improvements:
* …
> More unit tests

- .vscode/settings.json
- ardupilot_methodic_configurator/middleware_software_updates.py
- tests/test_frontend_tkinter_template_overview.py
- tests/test_middleware_software_updates.py
This pull request to `ardupilot_methodic_configurator/middleware_software_updates.py` includes changes to improve the robustness and error handling of the `_perform_download` method. The most important changes include prioritizing `.exe` files for Windows installations, adding additional error handling, and logging more specific error messages.
Improvements to Windows installation:
* Prioritized `.exe` files when selecting assets for Windows installations to ensure the correct file type is used. If no `.exe` files are found, the first available asset is used as a fallback.
Enhanced error handling and logging:
* Added specific error handling for general exceptions during the Windows download process and pip installation, with corresponding error messages to improve debugging and user …
> Add more tests, and make the code more robust

- tests/test_backend_flightcontroller.py
- tests/test_backend_flightcontroller_info.py
This pull request includes a minor change to the `tests/test_backend_flightcontroller.py` file. The change corrects the description comment to accurately reflect the file being tested. 
* [`tests/test_backend_flightcontroller.py`](diffhunk://#diff-35bd4b36bd97e902694e4fe943b0a6409af90f0f40fcb490b2ed1612740cac44L4-R4): Updated the comment to correctly reference `backend_flightcontroller.py` instead of `backend_filesystem.py`.
> Add pytests

- pytest.ini
- tests/test_frontend_tkinter_directory_selection_integration.py
This pull request includes a change to the `pytest.ini` file to improve test categorization by adding a new marker for integration tests.
Test configuration improvements:
* [`pytest.ini`](diffhunk://#diff-fb6a686182f16eb54af3c628f38593f347f68aba31de903983023c560288d7a1R6-R7): Added a new marker `integration` to categorize and mark tests as integration tests.
> Add integration tests

- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
- tests/test_frontend_tkinter_template_overview.py
This pull request focuses on improving code readability and simplifying logic in the `ardupilot_methodic_configurator` module, as well as cleaning up test files by removing redundant pylint suppressions. The key changes include replacing unnecessary conditional checks, streamlining tooltip logic, and refining test code.
* Simplified the retrieval of `doc_tooltip` in `__update_table` by using a default value directly in the `get` method, removing redundant conditional checks (`ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py`, [ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.pyL185-R188](diffhunk://#diff-a1fc77b2f824d73d73195abb5559fad566982d510708937a5c52ba2c86de71acL185-R188)).
* Removed unnecessary conditional checks for `param_metadata` …
> Code simplification and pyright linter fixes

- TUNING_GUIDE_ArduCopter.md
- USECASES.md
This pull request includes updates to documentation files to improve clarity and provide additional guidance for users. The most important changes include removing an unused image reference in the tuning guide and adding detailed recommendations for parameter management in the use cases guide.
* [`TUNING_GUIDE_ArduCopter.md`](diffhunk://#diff-25057261d62a266a9e263de6a22afbff4c4b7d12ea12f4c4bbb4a6ff32012b4fL412-L413): Removed a reference to an unused image (`mp_logging_bitmask.png`) to streamline the tuning guide.
* [`USECASES.md`](diffhunk://#diff-4e820b515938539a318b7a796ae98a44f3f4968e82ea5be4ca8f7552b4dfa340R21-R30): Added recommendations for starting with default parameter values and provided a link to ArduPilot documentation on resetting parameters, offering clearer guidance for new …
> Remove outdated and misleading screenshot.

- .github/dependabot.yml
- .github/workflows/dependabot-apt-update.yml
- .github/workflows/i18n-extract.yml
- .github/workflows/update_mo_files.yml
This pull request introduces updates to the Dependabot configuration, adds a new workflow for tracking apt package updates, and pins specific versions of the `gettext` package in existing workflows. These changes aim to improve dependency management and ensure consistency in the development environment.
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R10): Added a limit of 10 open pull requests for Dependabot and allowed updates for all dependency types. Introduced a new monthly update schedule for `github-actions` dependencies in the `.github/workflows` directory. [[1]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R10) [[2]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89dda …
> More version pinning and automated updates

- ardupilot_methodic_configurator/locale/de/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/it/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/ja/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/pt/LC_MESSAGES/ardupilot_methodic_configurator.po
- ardupilot_methodic_configurator/locale/zh_CN/LC_MESSAGES/ardupilot_methodic_configurator.po
This pull request updates translations for error messages in the `ardupilot_methodic_configurator` project across multiple languages. The changes provide localized strings for untranslated messages related to software updates, improving user experience for non-English speakers.
* **German (`de`)**:
- Added translations for messages related to Windows installation, download errors, and pip installation.
* **Italian (`it`)**:
- Added translations for similar messages, including errors during Windows download and pip installation.
* **Japanese (`ja`)**:
- Provided translations for error messages concerning Windows installation, download, and pip installation.
* **Portuguese (`pt`)**:
- Localized error messages regarding Windows installation, download, and pip installation.
* **Simplified …
> Updated translation strings

- .github/workflows/pylint.yml
- pyproject.toml
- scripts/crawl_ardupilot_wiki.py
- scripts/crawl_github_ardupilot.sh
This pull request introduces several updates, including dependency adjustments, project configuration changes, and the addition of new scripts for crawling ArduPilot-related documentation and GitHub repositories. The most notable changes focus on enhancing functionality for documentation processing and ensuring proper dependency management.
* Updated the `pylint` workflow to install the `scripts` dependency group in addition to `dev` for improved compatibility with new scripts. (`.github/workflows/pylint.yml`, [.github/workflows/pylint.ymlL43-R43](diffhunk://#diff-3fb2867e4a7c0ecbfdf0f36a3078f1689dca17453c5e0ebdd0671bb94733b5a3L43-R43))
* Added a new `scripts` dependency group in `pyproject.toml`, which includes the `bs4` package for HTML parsing. (`pyproject.toml`, …
> Added scripts that feed the gurubase.io RAG AI tool

- .github/dependabot.yml
- .github/workflows/update_vehicle_templates.yml
This pull request includes updates to the Dependabot configuration and workflow triggers to improve dependency management and workflow execution control.
* Removed a redundant `github-actions` package-ecosystem entry for the root directory in `.github/dependabot.yml`. This simplifies the configuration by retaining only the relevant entry for workflows under `/.github/workflows`.
* Updated the `push` trigger in `.github/workflows/update_vehicle_templates.yml` to include the `master` branch, ensuring the workflow runs only for changes pushed to the `master` branch.
> ci(update vehicle templates): only update them on the master branch

- ardupilot_methodic_configurator/backend_flightcontroller.py
Closes #407
This pull request enhances error handling in the `__create_connection_with_retry` method by providing user-friendly guidance for specific connection errors. The changes aim to improve the debugging experience, especially for common issues like permission errors on Linux systems.
* `ardupilot_methodic_configurator/backend_flightcontroller.py`:
- Modified the `__create_connection_with_retry` method to include additional guidance in the returned error message when a connection error occurs. The guidance is generated based on the error type and device information.
- Added a new private method `__get_connection_error_guidance` to provide tailored guidance for specific error types, such as suggesting the addition of a user to the `dialout` group for permission errors on Linux.
> fix(flight controller): fix issue #407

- .github/workflows/dependabot-apt-update.yml
This pull request updates the GitHub Actions workflow configuration for `dependabot-apt-update` by adding permissions to enhance security and functionality.
* [`.github/workflows/dependabot-apt-update.yml`](diffhunk://#diff-e099fd6fa1c015c032d0c543d91235b3572c3bfeb96b53300b3d41054ef122b2R8-R15): Added `permissions` at the workflow level with `contents: read` to limit access to repository contents and at the job level with `issues: write` to allow the job to create or modify issues.
> ci(permissions): restricted permisions

- ardupilot_methodic_configurator/frontend_tkinter_directory_selection.py
- ardupilot_methodic_configurator/frontend_tkinter_template_overview.py
- tests/test_frontend_tkinter_template_overview.py
This pull request introduces significant enhancements to the `TemplateOverviewWindow` class and related components in the `ardupilot_methodic_configurator` module. The changes focus on improving code modularity, testability, and user experience by refactoring methods, adding new functionality, and updating the application's logging and main entry point.
* Refactored `TemplateOverviewWindow` methods by introducing helper methods such as `_setup_treeview`, `_populate_treeview`, `_bind_events`, and `_adjust_treeview_column_widths` to improve code readability and maintainability. [[1]](diffhunk://#diff-478c6b619593c0326b286fd054ee544e8b621ed92993649a869c3bf83223a319L66-R90) [[2]](diffhunk://#diff-478c6b619593c0326b286fd054ee544e8b621ed92993649a869c3bf83223a319L102-R205)
* Replaced private …
> Refractor template overview and add more tests

- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
This pull request introduces enhancements to the parameter editor table in the `ardupilot_methodic_configurator` to better handle "forced" and "derived" parameters. The changes include new logic for displaying derived parameters, error handling for invalid edits, and improved metadata handling.
* Added a new flag `present_as_derived` to distinguish derived parameters from forced ones, and updated the logic to set this flag accordingly. (`[[1]](diffhunk://#diff-a1fc77b2f824d73d73195abb5559fad566982d510708937a5c52ba2c86de71acR309)`, `[[2]](diffhunk://#diff-a1fc77b2f824d73d73195abb5559fad566982d510708937a5c52ba2c86de71acL322-R323)`)
* Updated the styling logic for parameter entries to account for both forced and derived parameters, ensuring derived parameters are visually distinct. …
> Warn the users when they try to edit non-editable parameters

- .github/dependabot.yml
- TUNING_GUIDE_ArduCopter.md
- TUNING_GUIDE_ArduPlane.md
- TUNING_GUIDE_Heli.md
- TUNING_GUIDE_Rover.md
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
This pull request focuses on improving the clarity and consistency of instructions in the tuning guides for ArduCopter, ArduPlane, and Heli. It also removes unnecessary configuration from `.github/dependabot.yml`. The most important changes involve standardizing user prompts and enhancing documentation details.
**Standardization of User Prompts:**
* Updated all instances of prompts in `TUNING_GUIDE_ArduCopter.md`, `TUNING_GUIDE_ArduPlane.md`, and `TUNING_GUIDE_Heli.md` to use consistent phrasing: "When asked *Update file with values from FC?*" instead of the previous "Should the FC values now be copied to..." phrasing. This improves clarity and aligns instructions across guides. [[1]](diffhunk://#diff-25057261d62a266a9e263de6a22afbff4c4b7d12ea12f4c4bbb4a6ff32012b4fL298-R298) …
> Update the change reason tooltip when the param value changes

- .github/workflows/windows_build.yml
- pyproject.toml
This pull request updates the build process for Windows and adds a new dependency group for Windows-specific distributions. The most important changes involve switching to the `astral-sh/setup-uv` action in the GitHub workflow and defining a `win_dist` dependency group in `pyproject.toml`.
* [`.github/workflows/windows_build.yml`](diffhunk://#diff-4f99d7a5ccc527af64c0d4fca4d4065b5400c04c60f188181d532fcbc0a5af8eL39-L58): Replaced the `actions/setup-python` action with `astral-sh/setup-uv` to manage Python setup and environment activation. Simplified dependency installation by using the `win_dist` group from `pyproject.toml`.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R82-R89): Added a new `win_dist` dependency group containing …
> Generate GitHub Actions build provenance

- .codespell-exclude-file
- .github/workflows/codespell.yml
- REUSE.toml
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Hoverit_X13/15_motor.param
This pull request introduces updates to improve spelling consistency, enhance configuration files, and refine parameter documentation. The most important changes include updates to the `.codespell-exclude-file`, `.github/workflows/codespell.yml`, and `REUSE.toml` files, as well as improvements in parameter descriptions for the ArduCopter vehicle template.
* [`.codespell-exclude-file`](diffhunk://#diff-843bd8db7e4182a994e642ca3428785486b7082ab6e333d4e5efe830045790c9L5): Corrected a spelling issue in the excluded words list, ensuring better alignment with the codespell configuration.
* [`.github/workflows/codespell.yml`](diffhunk://#diff-ce84a1b2c9eb4ab3ea22f610cad7111cb9a2f66365c3b24679901376a2a73ab2L35-R35): Added `intoto` to the `ignore_words_list` to exclude it from codespell checks.
* …
> Clean up all spelling issues

- .github/workflows/generate_apm.pdef.xml.yml
- scripts/generate_pdef.xml_metadata.py
- tests/test_frontend_tkinter_show.py
…
This pull request introduces a new workflow and script to automate the generation and synchronization of `apm.pdef.xml` metadata files for various ArduPilot vehicle types. The workflow triggers the script, which generates parameter metadata for specific firmware versions and syncs the results to a remote server. Below are the key changes:
* Added `.github/workflows/generate_apm.pdef.xml.yml` to define a workflow for generating `apm.pdef.xml` metadata files. The workflow supports manual triggers (`workflow_dispatch`) and includes steps for setting up the environment, checking out repositories, and running the metadata generation script.
* Introduced `scripts/generate_pdef.xml_metadata.py`, a Python script that:
- Generates `apm.pdef.xml` files for different ArduPilot vehicle types and …
> Automate the generation of version-dependent apm.pdef.xml files

- ardupilot_methodic_configurator/frontend_tkinter_show.py
- tests/test_frontend_tkinter_show.py
This pull request refactors the tooltip functionality in `ardupilot_methodic_configurator/frontend_tkinter_show.py` to better handle platform-specific behavior, particularly distinguishing between macOS and non-macOS environments. The updates improve the clarity and maintainability of the code while addressing platform compatibility.
* Added conditional logic to bind different event handlers for macOS (`<Enter>` triggers tooltip creation and display, `<Leave>` triggers destruction) versus non-macOS systems (tooltip is created immediately and shown/hidden on events). (`[ardupilot_methodic_configurator/frontend_tkinter_show.pyR59-L65](diffhunk://#diff-2d5cb4788c5ffbd42523cde39b0448b88935e67ddf3d6699ef0d355c157b4270R59-L65)`)
* Introduced `create_show` and `destroy_hide` methods for …
> Fix a regression introduced in 1.4.6 while trying to fix macOS

- .github/workflows/mypy.yml
- .github/workflows/ruff.yml
This pull request updates the versions of dependencies used in GitHub Actions workflows for linting with `mypy` and `ruff`.
Dependency updates:
* [`.github/workflows/mypy.yml`](diffhunk://#diff-07730f31c368f5e0af82cb7d820dc37ae6a752a0a226f7aee9ebac72dfe41459L31-R31): Updated `mypy` to version `1.16.0` and `types-requests` to version `2.32.0.20250602`.
* [`.github/workflows/ruff.yml`](diffhunk://#diff-2648f2b57520d4056946a7e509a50cfed47a7a8b389c0861011416ba78ae0db5L38-R38): Updated `ruff` to version `0.11.13`.
> feat(ruff,mypy): Update ruff and mypy versions

- .github/workflows/pytest.yml
This pull request updates the test coverage thresholds in the GitHub Actions workflow configuration to enforce stricter standards for code quality.
Updates to test coverage thresholds:
* [`.github/workflows/pytest.yml`](diffhunk://#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL161-R161): Increased the `--fail-under` threshold in the `coverage report` command from 55% to 73%.
* [`.github/workflows/pytest.yml`](diffhunk://#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aL252-R252): Updated the `thresholdAll` parameter for coverage reporting from 60% to 73%.
> Increase test coverage minimum threshold to 73%

- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/backend_flightcontroller.py
- ardupilot_methodic_configurator/frontend_tkinter_connection_selection.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py
- tests/test__main__.py
- tests/test_backend_flightcontroller.py
This pull request introduces support for configuring the baud rate for MAVLink serial connections to the flight controller, along with improvements to the `FlightController` class and its usage across the codebase. The changes include adding a `baudrate` parameter with a default value, updating related methods to use this parameter, and adjusting tests accordingly.
* [`ardupilot_methodic_configurator/backend_flightcontroller.py`](diffhunk://#diff-289e82157f271122ec2b5c50452ffe6b9f0f8226ce1ac9b8bd414dba90825376R63-R66): Added `DEFAULT_BAUDRATE` and `DEFAULT_REBOOT_TIME` constants. Updated the `FlightController` class to include a `baudrate` parameter with a default value, and modified the `__create_connection_with_retry` method to use this parameter when establishing connections. …
> Support configurable FC baudrate

- scripts/crawl_ardupilot_wiki.py
OPTIONAL!!!  This is an approach that I have found useful for scripts with PyPI dependencies.
https://peps.python.org/pep-0723 enables Python files to have a header like:
```python
```
which enables:
`pipx run scripts/crawl_ardupilot_wiki.py` or
`uv run --script scripts/crawl_ardupilot_wiki.py`.
When this command is run, `pipx` or `uv` will import the dependencies from PyPI, put them in an isolated `venv`, and then run the script in that `venv`.
https://thisdavej.com/share-python-scripts-like-a-pro-uv-and-pep-723-for-easy-deployment
> Add PEP 723 header to scripts/crawl_ardupilot_wiki.py

- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/frontend_tkinter_template_overview.py
- tests/test__main__.py
- tests/test_frontend_tkinter_template_overview.py
This pull request refactors the terminology and logic in the codebase and tests to replace "firmware" with "vehicle" for better clarity and alignment with the domain. Additionally, it updates the filtering logic to use prefix matching instead of substring matching for vehicle types.
* Replaced "firmware" with "vehicle" in variable names, function names, and test descriptions for consistency (`tests/test_frontend_tkinter_template_overview.py`). [[1]](diffhunk://#diff-801d6f21a04c4dd66dc166912bbb413394f34b6ef6e5ebb7bfb6fe62284e0340L96-R97) [[2]](diffhunk://#diff-801d6f21a04c4dd66dc166912bbb413394f34b6ef6e5ebb7bfb6fe62284e0340L110-R112) [[3]](diffhunk://#diff-801d6f21a04c4dd66dc166912bbb413394f34b6ef6e5ebb7bfb6fe62284e0340L126-R126) …
> Refactored the file for testability and added many behaviour-tests

- .github/workflows/mypy.yml
- .github/workflows/pylint.yml
- .github/workflows/pyright.yml
- .github/workflows/ruff.yml
- ardupilot_methodic_configurator/annotate_params.py
- ardupilot_methodic_configurator/backend_filesystem.py
- extract_missing_translations.py
- pyproject.toml
- scripts/crawl_ardupilot_wiki.py
- tests/test_backend_filesystem.py
- tests/test_battery_cell_voltages.py
This pull request streamlines the Ruff linting workflow in GitHub Actions and updates the Ruff dependency to a newer version. The most important changes include replacing custom linting commands with the official Ruff GitHub Action and upgrading Ruff in the `pyproject.toml` file.
* [`.github/workflows/ruff.yml`](diffhunk://#diff-2648f2b57520d4056946a7e509a50cfed47a7a8b389c0861011416ba78ae0db5L22-L24): Removed the Python version matrix and the manual installation of Ruff. Replaced custom commands for linting and format checking with the `astral-sh/ruff-action` GitHub Action. [[1]](diffhunk://#diff-2648f2b57520d4056946a7e509a50cfed47a7a8b389c0861011416ba78ae0db5L22-L24) [[2]](diffhunk://#diff-2648f2b57520d4056946a7e509a50cfed47a7a8b389c0861011416ba78ae0db5L35-R38)
* …
> Use astral-sh/ruff-action with no explicit version

- .github/workflows/bump_version_and_tag.yml
- .github/workflows/i18n-extract.yml
- .github/workflows/mypy.yml
- .github/workflows/pytest.yml
- ardupilot_methodic_configurator/annotate_params.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- ardupilot_methodic_configurator/frontend_tkinter_pair_tuple_combobox.py
- pyproject.toml
This pull request introduces changes to improve dependency management in GitHub workflows by dynamically detecting versions from `pyproject.toml`, adjusts import handling in Python scripts to include `noqa` comments for specific linting rules, and updates the `pyproject.toml` configuration to remove `PLC0415` rule exclusions. Below are the key changes grouped by theme:
* Updated `.github/workflows/bump_version_and_tag.yml` to dynamically detect and install specific versions of `pip` and `packaging` from `pyproject.toml`. Fallbacks to latest versions are provided with warnings if detection fails.
* Updated `.github/workflows/i18n-extract.yml` to dynamically detect and install specific versions of `pip` and `python-gettext` from `pyproject.toml`. Fallbacks to default versions are provided …
> Misc fixes

- .github/workflows/windows_build.yml
This pull request updates the Inno Setup installer version in the Windows build workflow.
* [`.github/workflows/windows_build.yml`](diffhunk://#diff-4f99d7a5ccc527af64c0d4fca4d4065b5400c04c60f188181d532fcbc0a5af8eL50-R50): Updated the download URL for the Inno Setup installer from version 6.3.3 to version 6.4.3 to ensure the workflow uses the latest version.
> Update to version 6.4.3. Version 6.3.3 is no longer available

- ardupilot_methodic_configurator/__main__.py
- tests/test__main__.py
The user needs to enter the component data before proceeding, skipping is not an option
This pull request refines the logic in the `component_editor` function within `ardupilot_methodic_configurator/__main__.py` to ensure that the component editor is only skipped under specific conditions.
* Updated the condition for skipping the component editor to include additional checks. The editor is now skipped only if `state.args.skip_component_editor` is true and the `vehicle_dir_window` has a valid `configuration_template` and non-empty `blank_component_data`.
> Do not skip component editor if blanking component data was selected

- ardupilot_methodic_configurator/backend_filesystem.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
implements #481
This pull request introduces a new feature to format and display parameter tooltips with numeric sorting, enhancing the usability and clarity of tooltips in the parameter editor. The most important changes include the addition of a helper method for formatting values into numerically sorted columns, updates to parameter metadata to include these sorted tooltips, and modifications to the frontend to use the new tooltips.
* **Added `_format_columns_sorted_numerically` method**: This helper method formats a dictionary of values into column-major, horizontally aligned columns sorted numerically by key. It handles both numeric and string sorting, ensures optimal column width, and adjusts the number of columns dynamically. …
> Sort the current value tooltip numerically.

- ardupilot_methodic_configurator/data_model_vehicle_components_validation.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- tests/test_data_model_vehicle_components_validation_bdd.py
- tests/test_frontend_tkinter_component_editor.py
This pull request introduces several enhancements and fixes to the Ardupilot Methodic Configurator, focusing on data validation, frontend behavior, and test coverage. Key changes include expanding validation logic for vehicle component data, improving combobox validation in the frontend, and adding comprehensive test cases for validation scenarios.
* Added validation for entry limits and battery cell voltages in `validate_all_data`, including error handling and automatic correction of invalid values. (`ardupilot_methodic_configurator/data_model_vehicle_components_validation.py`)
* Improved combobox validation to handle dropdown state correctly, ensuring invalid values are only flagged when the dropdown is open. (`ardupilot_methodic_configurator/frontend_tkinter_component_editor.py`)
* …
> Validate all component data before saving

- tests/conftest.py
- tests/test_frontend_tkinter_base_window.py
- tests/test_frontend_tkinter_component_editor_integration.py
- tests/test_frontend_tkinter_component_template_manager.py
- tests/test_frontend_tkinter_directory_selection.py
- tests/test_frontend_tkinter_directory_selection_integration.py
- was caused by multiple test files trying to create separate Tk instances in a headless environment
- Moved the robust root fixture to conftest.py - This eliminates code duplication and ensures consistency
- Session-scoped fixture - Prevents multiple Tk instance creation across test sessions
- Robust error handling - Uses contextlib.suppress() for graceful cleanup
- Smart root reuse - Tries to reuse existing root or creates new one safely
> test(pytest): The tkinter initialization error

- ardupilot_methodic_configurator/data_model_vehicle_components_base.py
- tests/conftest.py
- tests/test_backend_filesystem.py
- tests/test_configuration_steps_schema.py
- tests/test_frontend_tkinter_autoresize_combobox.py
- tests/test_frontend_tkinter_component_editor_integration.py
- tests/test_frontend_tkinter_component_template_manager.py
- tests/test_frontend_tkinter_directory_selection_integration.py
- tests/test_frontend_tkinter_parameter_editor.py
This pull request addresses various pylint warnings and code quality issues across the test suite and a single source file. The changes focus on improving code style compliance without affecting functionality.
- Migrates unittest-based tests to pytest framework for consistency
- Fixes pylint warnings including unused imports, variable naming, and disable directive improvements
- Enhances test organization with proper fixture usage
> Pylint fixes

- .pre-commit-config.yaml
- ardupilot_methodic_configurator/backend_filesystem_json_with_schema.py
The update_vehicle_templates.py script should not
produce files that conflict with the pre-comit rules
> fix(pre-commit): It should not "fix" .svg files

- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
This PR fixes a typo that could cause potential crashes.
Also, this PR fixes an 'SLF001 Private member accessed' issue within the pre-commit-hooks.
> fix: correct background color typo and initialize parameter value to zero

- .github/workflows/pytest.yml
- tests/test_frontend_tkinter_rich_text.py
This pull request updates the workflow configuration in `.github/workflows/pytest.yml` to integrate with the `uv` tool for managing Python environments, replacing the previous `actions/setup-python` step. This change simplifies environment setup and dependency installation.
* Replaced `actions/setup-python` with `astral-sh/setup-uv` to manage Python environments, enabling the `activate-environment` option for seamless integration.
* Updated the dependency installation process to use `uv pip install` instead of directly invoking `pip`, aligning with the `uv` tool's workflow.
> Use uv to install pytest environment

- .github/workflows/bump_version_and_tag.yml
- ardupilot_methodic_configurator/data_model_vehicle_components_base.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- tests/test_data_model_vehicle_components_templates.py
- tests/test_frontend_tkinter_component_editor_base.py
This PR refactors the component editor to improve the save workflow and data model structure. The changes focus on separating validation from save operations and improving project state tracking.
- Renamed and refactored the save validation method to clarify its purpose
- Replaced template-based project tracking with a dedicated new project flag
- Updated tests to reflect the new save workflow
> Refactor component editor

- ardupilot_methodic_configurator/backend_flightcontroller.py
> If no FC is detected on the serial ports, try the network ports

- .gitignore
- ardupilot_methodic_configurator/frontend_tkinter_component_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_pair_tuple_combobox.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
- tests/test_frontend_tkinter_pair_tuple_combobox.py
- tests/test_frontend_tkinter_parameter_editor_table.py
This PR fixes an issue where the main window would not scroll when the mouse cursor was hovering over child widgets like text entries (ttk.Entry) and labels. #460 
This implementation adopts the improved approach suggested by @amilcarlucas  in the issue comments.
Closes #460.
Note: The test_user_benefits_from_consistent_ui_styling test appears to be failing on the main branch and is unrelated to these changes.
> Scroll with mouse wheel does not work over labels and text fields in components and in parameters #460

- .github/workflows/i18n-extract.yml
- pyproject.toml
- Integrate GitHub AI inference action with GPT-4o for automated translations
- Add support for 5 languages: Portuguese, German, Italian, Japanese, Chinese
- Implement professional translation prompts with aviation/drone context
- Add language-specific guidelines (European Portuguese, formal German, etc.)
- Automate complete translation pipeline: extract → translate → insert → compile
- Enhance PR descriptions with AI translation details and review requirements
- Add documentation for AI prompt templates in .github/prompts/
The workflow now automatically processes missing translations using AI while preserving placeholders, line numbers, and technical terminology. Human review is still required for quality assurance and cultural appropriateness.
> Add AI-powered translation automation to i18n workflow

- ARCHITECTURE_motor_test.md
- ardupilot_methodic_configurator/backend_filesystem_program_settings.py
- ardupilot_methodic_configurator/backend_flightcontroller.py
- ardupilot_methodic_configurator/data_model_motor_test.py
- scripts/batch_convert_motor_diagrams.py
- scripts/download_motor_diagrams.py
- tests/test_backend_filesystem_program_settings.py
- tests/test_backend_flightcontroller.py
- tests/test_data_model_motor_test.py
A comprehensive motor test business logic for ArduPilot flight controllers, implementing the complete model in a Model-View architecture with robust testing capabilities. The implementation adds motor testing functionality, frame configuration management, battery safety monitoring
-    Motor test implementation with safety features and real-time feedback
-    Exception-based error handling refactoring in data model with comprehensive validation
> Motor test backend
