- MethodicConfigurator/backend_flightcontroller.py
- MethodicConfigurator/backend_mavftp.py
validate consistency between datasources
print parts of the banner into the console
> IMPROVEMENT: Use FC banner messages to determine the FC name

- 24_inflight_magnetometer_fit_setup.pdef.xml
Per request: https://github.com/ArduPilot/ardupilot/pull/26914#issuecomment-2343291742
> Templates: add advance-wp.lua applet params

- .pre-commit-config.yaml
- .vscode/launch.json
- MethodicConfigurator/frontend_tkinter_component_editor_base.py
- MethodicConfigurator/frontend_tkinter_connection_selection.py
- MethodicConfigurator/frontend_tkinter_pair_tuple_combobox.py
- MethodicConfigurator/frontend_tkinter_parameter_editor_table.py
Moved combobox code to a new file to make it easier to test
fixes #61
> IMPROVEMENT: Use wider combobox listbox if necessary

- MethodicConfigurator/locale/zh_CN/LC_MESSAGES/MethodicConfigurator.po
Line 416 is not translated, 
`#: MethodicConfigurator/frontend_tkinter_base.py:262
msgid "Lifting window: {_e} on file {__file__}"
msgstr "Lifting window: {_e} on file {__file__}"`
I do not quiet understand the meaning of it for now. 
Everything else is translated and I think is decent, but I did not try compling and running it. 
Will mark this as WIP, some format might need to be changed.I'm a little busy recently so sorry for the delay and not able to test.
Will continue work on it.
> Add simplified Chinese translation

- README.md
Explain the lua scripts are automatically installed
> Improve a link

- .coveragerc
- .github/workflows/pytest.yml
required for proper covaralls.io links to source code
> Fix the source file path in the coverage.xml report

- ardupilot_methodic_configurator/configuration_steps_ArduCopter.json
- ardupilot_methodic_configurator/configuration_steps_ArduPlane.json
- ardupilot_methodic_configurator/configuration_steps_Heli.json
- ardupilot_methodic_configurator/configuration_steps_Rover.json
- ardupilot_methodic_configurator/vehicle_templates/Heli/OMP_M4/configuration_steps_Heli.json
It causes issues in the webtool
> fix(configuration_steps): disable the fast harmonic notch logging bit

- ardupilot_methodic_configurator/configuration_steps_ArduCopter.json
- ardupilot_methodic_configurator/configuration_steps_ArduPlane.json
- ardupilot_methodic_configurator/configuration_steps_Heli.json
- ardupilot_methodic_configurator/configuration_steps_Rover.json
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_documentation_frame.py
- ardupilot_methodic_configurator/vehicle_templates/Heli/OMP_M4/configuration_steps_Heli.json
- tests/test_frontend_tkinter_parameter_editor_documentation_frame.py
It causes issues in the webtool
> Disable the fast harmonic notch logging bit

- TUNING_GUIDE_ArduCopter.md
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
- ardupilot_methodic_configurator/vehicle_components_schema.json
The outdated templates have some fields missing. Ignore that as the fields will be automatically added anyway
> Creating new projects from outdated template files

- ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Chimera7/vehicle_components.json
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/FETtec-5/vehicle_components.json
This pull request includes changes to the `ardupilot_methodic_configurator` project, focusing on temporarily disabling validation in the backend and updating vehicle component specifications in JSON templates.
Backend changes:
* [`ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py`](diffhunk://#diff-4d082af14c1239b3a9772b04b19d0ba7bc6a11c6675c8dae7d127dcb65ab7d92L112-R117): Commented out the validation logic in the `save_vehicle_components_json_data` method until a related pull request gets merged.
Vehicle template updates:
* [`ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Chimera7/vehicle_components.json`](diffhunk://#diff-c9afa5bbe10a3cf0e9f16e4797b0c4e5561335949205324c30a81a587606ddb5L156-R157): Updated the propeller model and added a URL for the …
> Fix regressions

- .github/workflows/i18n-extract.yml
- .github/workflows/update_mo_files.yml
Create a PR instead, so that it can be reviewed and so that the master branch can be set to protected Reduce the permissions and limit their scope
Create a single commit with both .pot and .po files Add labels to the PR
Improve the commit message
> ci(translations): Do not commit changes directly to master branch

- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/02_imu_temperature_calibration_setup.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/05_remote_controller.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/07_esc.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/08_batt1.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/14_logging.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/15_motor.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/16_pid_adjustment.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/17_remote_id.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/19_notch_filter_results.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/20_throttle_controller.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/53_everyday_use.param
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/vehicle_components.json
This pull request includes multiple changes to the configuration files for the Holybro X650 LTE vehicle template in the ArduCopter project. The changes primarily involve parameter adjustments to improve performance, logging, and safety features. Below is a summary of the most important changes:
* Updated `INS_TCAL1_TMAX`, `INS_TCAL2_TMAX`, and added `INS_TCAL3_TMAX` to use `BRD_HEAT_TARG` for consistency in temperature calibration settings.
* Enhanced logging settings to use batch logging for accelerometer and gyroscope on F4 processors.
* Added `PILOT_THR_BHV` parameter to configure throttle behavior.
* Adjusted `ATC_THR_MIX_MAN` and `PSC_ACCZ_I`, `PSC_ACCZ_P` parameters to improve throttle control based on learned hover values. …
> Update Holybro_X650_LTE template

- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/FETtec-5/vehicle_components.json
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X500_V2/vehicle_components.json
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Holybro_X650_LTE/vehicle_components.json
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/ReadyToSkyZD550/vehicle_components.json
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/Tarot_X4/vehicle_components.json
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/X11_plus/vehicle_components.json
- ardupilot_methodic_configurator/vehicle_templates/ArduCopter/diatone_taycan_mxc/4.5.x-params/vehicle_components.json
This pull request includes updates to the `vehicle_components.json` files across multiple vehicle templates within the `ardupilot_methodic_configurator` directory. The changes primarily involve updating product model names, URLs, and versions for various components. Additionally, the program version has been incremented from `1.2.1` to `1.2.2` in several templates.
Updates to product details:
* [`ardupilot_methodic_configurator/vehicle_templates/ArduCopter/FETtec-5/vehicle_components.json`](diffhunk://#diff-67d25117b503df2466b12b25521d55464e6b5976d7bb430e72972e1094a292f3L36-R37): Updated model names and URLs for "RC Controller", "Battery Monitor", "ESC", "Motors", and "GNSS Receiver" components. [[1]](diffhunk://#diff-67d25117b503df2466b12b25521d55464e6b5976d7bb430e72972e1094a292f3L36-R37) …
> Added and corrected URLs

- .github/workflows/update_vehicle_templates.yml
This pull request updates the workflow for updating vehicle templates. The most important changes include modifying the schedule for running the workflow, adding paths to trigger the workflow on push, and enhancing the job steps to stage changes and clean untracked files.
Workflow schedule and triggers:
* [`.github/workflows/update_vehicle_templates.yml`](diffhunk://#diff-7c38991ace082c212b93eaaf4c47c57b1253e060a15a5a5f69cae67a0c1b98b3L6-R10): Changed the cron schedule to run at 3:30 UTC on Monday, Wednesday, and Friday, and added paths to trigger the workflow on push to specific files.
Job enhancements:
* [`.github/workflows/update_vehicle_templates.yml`](diffhunk://#diff-7c38991ace082c212b93eaaf4c47c57b1253e060a15a5a5f69cae67a0c1b98b3L53-R57): Updated the job step to check for changes …
> Cleanup untracked files improve job triggers

- .github/workflows/pytest.yml
- tests/test_frontend_tkinter_entry_dynamic.py
This pull request includes updates to the GitHub Actions workflow configuration for running pytest. The changes enhance the permissions for pull request jobs and adjust the coverage thresholds.
Enhancements to GitHub Actions workflow:
* [`.github/workflows/pytest.yml`](diffhunk://#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aR205-R207): Added `contents: read` and `pull-requests: write` permissions to the job configuration to ensure the job has the necessary access rights.
* [`.github/workflows/pytest.yml`](diffhunk://#diff-2500680f4bc6c1b75c3d4b36372bf4d64c5f603b90bfd7a5186f66a20329d16aR223-R225): Set the coverage thresholds for all, new, and modified code to 0 to ensure the job does not fail due to coverage issues.
> Pytest improvements

- ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- ardupilot_methodic_configurator/vehicle_components_schema.json
Make it explicit which fields are optional
This pull request introduces several enhancements and new features to the `ardupilot_methodic_configurator` project. The changes focus on improving schema validation, adding detailed descriptions and optional status to schema properties, and enhancing the user interface with tooltips and optional field styles.
* Added descriptions and optional status to various properties in the `vehicle_components_schema.json` file to provide more context and improve documentation. [[1]](diffhunk://#diff-4715dbdf1fa30130fed55b4481a73accd616d905bee1c8f2503c7759491e6a9bL23-R72) [[2]](diffhunk://#diff-4715dbdf1fa30130fed55b4481a73accd616d905bee1c8f2503c7759491e6a9bL76-R183) [[3]](diffhunk://#diff-4715dbdf1fa30130fed55b4481a73accd616d905bee1c8f2503c7759491e6a9bL129-R …
> Add mouse-over tooltips to all component editor GUI elements

- ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- tests/test_frontend_tkinter_component_editor_base.py
This pull request includes several changes aimed at refactoring and improving the codebase, particularly focusing on simplifying methods and enhancing test coverage. The most important changes include the introduction of a new helper method for retrieving component schema property descriptions, refactoring of widget addition methods in the frontend, and the addition of new tests for these methods.
Refactoring and simplification:
* [`ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py`](diffhunk://#diff-4d082af14c1239b3a9772b04b19d0ba7bc6a11c6675c8dae7d127dcb65ab7d92R297-R313): Introduced `_get_component_schema_property_description` method to centralize logic for retrieving component schema property descriptions and updated various methods to use this new helper. …
> Pylint fixes and add more tests

- renovate-config.json
This pull request includes changes to the `renovate-config.json` file to update the configuration for dependency management. The most important changes include renaming a key, modifying the format of a configuration object, and adding a new field to an existing object.
Configuration updates:
* Renamed the `regexManagers` key to `customManagers` to better reflect its purpose.
* Reformatted the `pin` object to be more concise by placing the entire object on a single line.
* Added the `customType` field with the value `"regex"` to the objects within the `customManagers` array.
* Modified the `matchStrings` field to be an array of strings instead of a single string for better readability and maintainability.
> Migrate renovate configuration

- ardupilot_methodic_configurator/configuration_steps_ArduCopter.json
- ardupilot_methodic_configurator/configuration_steps_ArduPlane.json
- ardupilot_methodic_configurator/configuration_steps_Heli.json
- ardupilot_methodic_configurator/configuration_steps_Rover.json
- ardupilot_methodic_configurator/configuration_steps_strings.py
- ardupilot_methodic_configurator/middleware_fc_ids.py
- ardupilot_methodic_configurator/vehicle_templates/Heli/OMP_M4/configuration_steps_Heli.json
- pyproject.toml
- update_flight_controller_ids.py
This pull request includes several corrections to spelling and formatting in multiple configuration files for different vehicle types, as well as some minor adjustments to the project configuration.
Corrections to spelling and formatting:
* [`ardupilot_methodic_configurator/configuration_steps_ArduCopter.json`](diffhunk://#diff-28a03f4b8f63cc3e92b2c8996222fc15d585387408e91b5fbec05b735eaf8a77L233-R233): Corrected "autonuned" to "autotuned" and "Windspeed Estimation" to "wind speed estimation". [[1]](diffhunk://#diff-28a03f4b8f63cc3e92b2c8996222fc15d585387408e91b5fbec05b735eaf8a77L233-R233) [[2]](diffhunk://#diff-28a03f4b8f63cc3e92b2c8996222fc15d585387408e91b5fbec05b735eaf8a77L606-R606) [[3]](diffhunk://#diff-28a03f4b8f63cc3e92b2c8996222fc15d585387408e91b5fbec05b735eaf8a77L639-R639)
* …
> Lint the generated file, but do not reformat it

- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
This pull request includes changes to improve the user interface and enhance the logic for setting parameter values in the `ardupilot_methodic_configurator` project. The most important changes include modifying the order of buttons in a custom dialog and refining the logic for updating parameter values.
Improvements to user interface:
* [`ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py`](diffhunk://#diff-66416537a8c3d05fc24b29ee4b158b15e4bade6fe86f9229e780081570a279b5L468-R468): Changed the order of buttons in the custom dialog to "Close, Yes, No" for better user experience.
Enhancements to parameter value logic:
* [`ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py`](diffhunk://#diff-a1fc77b2f824d73d73195abb5559fad566982d510708937a5c52ba2c86de …
> Regression causing it too ask too often if a file should be changed

- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/backend_filesystem.py
- tests/test__main__.py
- tests/test_annotate_params.py
- tests/test_backend_filesystem.py
This pull request introduces several new features and improvements to the `ardupilot_methodic_configurator` project. The key changes include the addition of a backup functionality for flight controller parameters, new utility functions for handling proxies, and comprehensive unit tests to ensure the robustness of these features.
* [`ardupilot_methodic_configurator/__main__.py`](diffhunk://#diff-07c8aae629798ce99b3a341b36fe9273c6afcf8de3d503dfbc9e720055f5630fR231-R239): Added incremental backup creation for flight controller parameters.
* [`ardupilot_methodic_configurator/backend_filesystem.py`](diffhunk://#diff-cf28409654b00ab8706721d7366feaf693978b04612204ba7b945adac7563716R765-R780): Introduced `find_lowest_available_backup_number` method to find the next available backup number.
* …
> Autobackup FC parameters when the program is opened and an FC is connected

- .coveragerc
- ardupilot_methodic_configurator/configuration_steps_strings.py
- ardupilot_methodic_configurator/frontend_tkinter_progress_window.py
- ardupilot_methodic_configurator/frontend_tkinter_stage_progress.py
- update_configuration_steps_translation.py
This pull request includes several changes to improve the `ardupilot_methodic_configurator` project, focusing on updating configuration step strings, enhancing the translation extraction process, and refining the Tkinter frontend. Below are the most important changes:
* Added multiple new configuration step strings to the `configuration_steps_strings` function to enhance the configurator's descriptive capabilities.
* Updated the `extract_strings_from_config_steps` function to extract phase names in addition to phase descriptions, ensuring all relevant strings are captured for translation.
* Modified the `_create_phase_frame` function to ensure phase names are translated if they exist, improving the localization of the Tkinter frontend.
* Updated the file docstring in …
> Misc fixes

- ardupilot_methodic_configurator/backend_internet.py
- ardupilot_methodic_configurator/frontend_tkinter_software_update.py
- tests/test_frontend_tkinter_software_update.py
This pull request includes several significant changes to the `ardupilot_methodic_configurator` project, including enhancements to the Windows installation process and the addition of comprehensive tests for the `ProgramSettings` class. Below are the most important changes:
* Added a detailed docstring to the `download_and_install_on_windows` function to describe its purpose, arguments, and return value.
* Replaced the direct execution of the installer with a batch file to handle the installation process, ensuring the main application exits properly before the installer runs. This change includes creating and executing the batch file and adding a brief sleep to allow callbacks to complete.
* Added a new test file `tests/test_backend_filesystem_program_settings.py` containing comprehensive …
> Update without closing

- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py
…
This pull request includes several changes to the `ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py` file to improve the parameter editor's functionality and user experience. The most important changes are the addition of a time-based check to reduce redundant save prompts and the introduction of a new attribute to track the last time the user was asked to save changes.
Improvements to parameter editor functionality:
* Added import for the `time` module to enable time-based checks.
* Introduced a new attribute `last_time_asked_to_save` to track when the user was last prompted to save changes.
* Updated the `write_changes_to_intermediate_parameter_file` method to include a time-based condition that reduces redundant prompts to save changes if the …
> If annotate_params is true, ask to write to file only once

- tests/test_backend_filesystem_configuration_steps.py
This pull request includes significant enhancements to the `tests/test_backend_filesystem_configuration_steps.py` file, focusing on expanding test coverage and improving error handling. The most important changes include the addition of new test cases, handling of various exceptions, and validation improvements.
* Added multiple new test cases to cover different scenarios, such as `test_re_init_file_not_found`, `test_compute_parameters_with_bitmask`, `test_auto_changed_by_nonexistent_file`, and others to ensure comprehensive testing of the `ConfigurationSteps` class.
* Introduced handling for `FileNotFoundError` and `JSONDecodeError` exceptions within the test cases to validate the robustness of the error handling mechanisms.
* Implemented logging checks to verify that appropriate …
> Add more tests

- tests/test_frontend_tkinter_directory_selection.py
Add tests for the directory selection file
> directory selection tests

- .github/workflows/dependabot-apt-update.yml
- SUPPORT.md
This pull request introduces a minor update to the GitHub Actions workflow for handling apt package updates and an enhancement to the support documentation by adding a new AI chatbot feature.
* [`.github/workflows/dependabot-apt-update.yml`](diffhunk://#diff-e099fd6fa1c015c032d0c543d91235b3572c3bfeb96b53300b3d41054ef122b2L23-R23): Updated the regex pattern in the `grep` command to improve compatibility by allowing a broader range of characters when extracting pinned apt package names.
* [`SUPPORT.md`](diffhunk://#diff-c5fe610b0215b144474106251cab954f8af55fe26cbd5d2265fd6ca19109c97bR8-R9): Added a new section to highlight the availability of an AI chatbot trained on the ArduPilot documentation, accessible via the "Ask AI" button in the MethodicConfigurator interface.
> Ai chatbot

- TUNING_GUIDE_ArduCopter.md
- TUNING_GUIDE_ArduPlane.md
- TUNING_GUIDE_Heli.md
- TUNING_GUIDE_Rover.md
closes #441
Thanks to Tim Archer for reporting
> fix(tuning guide): fix Documentation update for magfit Section 9.1.2

- INSTALL.md
- install_macos.sh
- install_windows.bat
This pull request introduces updates to installation scripts and documentation to improve clarity, streamline setup processes, and ensure compatibility with specific Python dependencies. Below is a summary of the most significant changes grouped by theme.
* Updated `INSTALL.md` to include additional instructions for macOS users, specifying the need to install `python-tk@3.9` using Homebrew for compatibility.
* Modified `install_macos.sh` to replace `python3 -m venv` with `uv venv --python 3.9` for virtual environment creation, ensuring compatibility with Python 3.9.
* Added installation of `python-tk@3.9` in `install_macos.sh` to handle potential GUI dependencies.
* Replaced direct `pip` commands with `uv pip` for package management, aligning with the updated virtual environment setup.
* …
> Improve macOS install instructions

- .github/workflows/windows_build.yml
This pull request enhances the Windows build workflow by improving provenance file handling and debugging. These changes aim to improve code quality and build transparency.
* [`.github/workflows/windows_build.yml`](diffhunk://#diff-4f99d7a5ccc527af64c0d4fca4d4065b5400c04c60f188181d532fcbc0a5af8eR108): Added an `id` to the "Generate GitHub Actions build provenance" step to enable referencing its outputs in subsequent steps.
* [`.github/workflows/windows_build.yml`](diffhunk://#diff-4f99d7a5ccc527af64c0d4fca4d4065b5400c04c60f188181d532fcbc0a5af8eR163-R198): Improved debugging for provenance file handling by introducing logic to verify the existence of the expected provenance file from the "Generate GitHub Actions build provenance" step. Added fallback mechanisms to search for provenance …
> SLSA new attempt

- ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py
- ardupilot_methodic_configurator/data_model_vehicle_components.py
- tests/test_data_model_vehicle_components.py
- update_vehicle_templates.py
This pull request refactors the handling of vehicle components data in the `update_vehicle_templates.py` script and improves type annotations in `VehicleComponents` to enhance code maintainability and type safety. The most important changes include replacing manual JSON structure updates with a dedicated data model class and refining type annotations in `VehicleComponents`.
* **Replaced manual JSON structure updates with `ComponentDataModel`:** The function `update_vehicle_components` was removed, and its logic was replaced by the `ComponentDataModel` class. This class encapsulates the logic for updating the vehicle components structure, improving modularity and readability. (`update_vehicle_templates.py`, [[1]](diffhunk://#diff-6aae4bc3789b2c7637a34d10f8d4ccae1ef36ef66c0f85451345f8fe70d09 …
> Create components data_model

- ARCHITECTURE.md
- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/backend_filesystem_program_settings.py
- ardupilot_methodic_configurator/backend_filesystem_vehicle_components.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_component_editor_base.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_documentation_frame.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor_table.py
- tests/test_backend_filesystem_program_settings.py
- tests/test_backend_filesystem_vehicle_components.py
- tests/test_frontend_tkinter_component_editor_base.py
- tests/test_frontend_tkinter_parameter_editor_table.py
- tests/test_integration_parameter_editor_table.py
This is the single most requested feature in this software.
This pull request introduces a new "GUI Complexity" setting to the ArduPilot Methodic Configurator, allowing users to toggle between "simple" and "normal" interface modes. It also adds functionality to dynamically modify schemas based on the "MCU Series" field and includes extensive UI updates and backend changes to support these features. Below are the most significant changes grouped by theme:
* Updated `SETTINGS_DEFAULTS` in `backend_filesystem_program_settings.py` to include the new `gui_complexity` setting, defaulting to "simple". Modified `get_setting` and `set_setting` methods to handle `str` values for settings. [[1]](diffhunk://#diff-de11579ee58da76c80ee1c640ec8e839ae14f8cd794eefba1a382d166405d6b9L30-R34) …
> UI complexity

- ardupilot_methodic_configurator/backend_flightcontroller_info.py
- ardupilot_methodic_configurator/frontend_tkinter_flightcontroller_info.py
- tests/test_backend_flightcontroller_info.py
- tests/test_frontend_tkinter_flightcontroller_info.py
This pull request refactors the flight controller information handling in the ArduPilot configurator, introducing a presenter class for better separation of concerns, improving testability, and enhancing the user interface logic. The key changes include the addition of a `FlightControllerInfoPresenter` class, improved logging and formatting functionality, and refactoring of the frontend logic to use the presenter.
* Added `log_flight_controller_info` and `format_display_value` methods to the backend for improved logging and consistent formatting of flight controller information. (`ardupilot_methodic_configurator/backend_flightcontroller_info.py`, [ardupilot_methodic_configurator/backend_flightcontroller_info.pyR254-R271](diffhunk://#diff-9830efe407684f09d96c151c2a2287c3c6a4b7a55f7e38735184 …
> More FC info tests

- .github/copilot-instructions.md
- .github/instructions/gui_translation_instructions.md
This pull request updates the `.github/copilot-instructions.md` file to improve documentation clarity and organization. The changes include adjustments to formatting and additional context for existing sections.
Documentation improvements:
* Enhanced the architecture section with better formatting for the list of components, improving readability.
* Reformatted the description of vehicle templates to split a long line into two for clarity.
* Added a blank line before the list of specific workflows to maintain consistent formatting and improve readability.
> Lint the .md file

- .github/workflows/python-publish.yml
- .github/workflows/update_vehicle_templates.yml
python 3.13.5 requires a venv to work properly
> Fix a python 3.13.5 regression

- TUNING_GUIDE_ArduCopter.md
- ardupilot_methodic_configurator/configuration_steps_ArduCopter.json
- ardupilot_methodic_configurator/configuration_steps_strings.py
> Add link to filter review documentation

- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/backend_flightcontroller.py
- ardupilot_methodic_configurator/frontend_tkinter_connection_selection.py
- tests/test_frontend_tkinter_connection_selection.py
- Add baudrate combobox to connection selection widget
Closes #801
> Add baudrate selection for device connections

- ardupilot_methodic_configurator/frontend_tkinter_flightcontroller_info.py
- tests/test_frontend_tkinter_flightcontroller_info.py
This prevents the progress bar form occluding the FC info
Closes #652
> Integrate parameter download progress bar into the FC info window

- ardupilot_methodic_configurator/frontend_tkinter_base_window.py
- ardupilot_methodic_configurator/frontend_tkinter_font.py
- ardupilot_methodic_configurator/frontend_tkinter_rich_text.py
> Add safe font functions to prevent TkDefaultFont errors on macOS

- .github/workflows/windows_build.yml
Authentication check - Verifies if GitHub token is available
Repository validation - Shows which repository we're querying
Exit code monitoring - Captures gh CLI exit codes for diagnosis
Detailed error messages - Shows both exceptions and command output
> Fix stable version detection

- ardupilot_methodic_configurator/__main__.py
- ardupilot_methodic_configurator/data_model_vehicle_project.py
- ardupilot_methodic_configurator/frontend_tkinter_directory_selection.py
- ardupilot_methodic_configurator/frontend_tkinter_parameter_editor.py
- ardupilot_methodic_configurator/frontend_tkinter_project_creator.py
- ardupilot_methodic_configurator/frontend_tkinter_project_opener.py
Separate business logic from UI logic
Separate "New project" into a different sub-application window
- This simplifies the UI making it clearer for newbie users
- Makes it easier to extend "New Project" Allows "open project" to be more easily extended in the future to include multiple last recent projects Increases the testability a lot, coverage should well above 84% now
> Refactor directory selection GUI code

- .github/workflows/frogbot-scan-and-fix.yml
This workflow automates the scanning and fixing of vulnerable project dependencies using JFrog Xray.
> Add Frogbot Scan and Fix GitHub Actions workflow
